### ISSUE TITLE
missing technique b0001.007?

### ISSUE THREAD

**Issue by lenz913** [MBCProject/mbc-markdown#168]
Hi, was looking through the behaviours under anti-behavioural analysis/debugger detection, and noted that .007 is not present?
Just want to clarify if this is a typo or a behaviour that was removed?

**Comment by brightmt** [comment]
Hi!  That's a good question.  I'll take a look and see if I can find anything in our old materials.

**Comment by brightmt** [comment]
Turns out B0001.007 existed at one point.

Here's the version of the file containing that method: https://github.com/MBCProject/mbc-markdown/blob/b7197c785d33cc3c1d121ba82732f62fb650a5cf/anti-behavioral-analysis/detect-debugger.md

And here's the version of the file where B0001.007 disappears: https://github.com/MBCProject/mbc-markdown/blob/e07e00f4d488bbba5540de72426ad12c9af045e9/anti-behavioral-analysis/debugger-detection.md

I didn't work on the MBC at this time, so take my insight with a grain of salt until someone with more expertise can confirm, but I suspect it was merged into .006 to create the more general method covering the fact there are multiple ways interrupts can be used to detect debuggers.  If you look at the file containing method .007 and the version of .006 in [B0001 on the main branch](https://github.com/MBCProject/mbc-markdown/blob/main/anti-behavioral-analysis/debugger-detection.md), it looks like .006 specifically notes that it includes both "Interrupt 0x2d" (formerly labeled as .006) and "Interrupt 1" formerly (.007).

**Comment by dzbeck** [comment]
@brightmt is correct. When methods are consolidated or removed, IDs that are no longer needed (such as B0001.007) are "revoked" and are not reused. Thanks for your question @lenz913 - going forward, we'll keep track of revoked IDs.
