### ISSUE TITLE
Content Wipe vs Data Destruction

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#27]
[Content wipe](https://github.com/MBCProject/mbc-markdown/blob/master/impact/disk-content-wipe.md) seems like it is a form of [Data destruction](https://github.com/MBCProject/mbc-markdown/blob/master/impact/data-destruction.md).  Should/could they be merged?

**Comment by dzbeck** [comment]
MBC sometimes further refines ATT&CK techniques, but doesn't generally merge ATT&CK techniques. The techniques are separate in ATT&CK, which says, "[Data Destruction] is distinct from Disk Content Wipe and Disk Structure Wipe because individual files are destroyed rather than sections of a storage disk or the disk's logical structure." However, maybe the MBC behavior "Disk Content Wipe" should be changed to "Disk Wipe" to include both disk structure and disk content wiping.

**Comment by malwarefrank** [comment]
Ok, that makes sense.  I missed that distinction in the wording.

I think then "Delete Shadow Drive" should be renamed to "Delete Shadow Copies" and moved to Data Destruction instead of Disk Wipe. The canonical name is Shadow Copy, unless you are referring to something else. And the action is through the OS on files, not directly against a drive.

**Comment by dzbeck** [comment]
that makes sense - i made the update. thanks!
